### ISSUE TITLE
XML with namespace and expression with attribute filter

### ISSUE THREAD

**Issue by lazize** [antchfx/xmlquery#1]
I don't know if I should open this issue here or on `xpath`, if it is wrong just let me know and I can close it here and open it there.

With the example below it demonstrate that expression like **`//node[@attr='value']`** will not work when `xml` uses `namespace` and you are selecting a node that belongs to this namespace.

How can I make it work?

```go
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/antchfx/xmlquery"
)

func main() {
	willWork()
	willFail()
}

func willWork() {
	fmt.Println("### WILL WORK")

	// Note: root node does not contain xmlns attribute
	xmlInput := `<root>
	  <myns:child id="1">value 1</myns:child>
	  <myns:child id="2">value 2</myns:child>
	</root>`

	reader := strings.NewReader(xmlInput)
	doc, err := xmlquery.Parse(reader)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	node := xmlquery.Find(doc, "//child[@id='1']")
	if node == nil {
		fmt.Println("ERROR - Not found")
	} else {
		fmt.Println("GOOD - Found")
		fmt.Println(len(node))
	}

	// Even though the expression above work, this one will fail
	node = xmlquery.Find(doc, "//myns:child[@id='1']")
	if node == nil {
		fmt.Println("ERROR - Not found")
	} else {
		fmt.Println("GOOD - Found")
		fmt.Println(len(node))
	}
}

func willFail() {
	fmt.Println("### WILL FAIL")

	// Note: root node contains xmlns attribute
	xmlInput := `<root xmlns:myns="bla bla bla">
	  <myns:child id="1">value 1</myns:child>
	  <myns:child id="2">value 2</myns:child>
	</root>`

	reader := strings.NewReader(xmlInput)
	doc, err := xmlquery.Parse(reader)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	node := xmlquery.Find(doc, "//child[@id='1']")
	if node == nil {
		fmt.Println("ERROR - Not found")
	} else {
		fmt.Println("GOOD - Found")
		fmt.Println(len(node))
	}

	node = xmlquery.Find(doc, "//myns:child[@id='1']")
	if node == nil {
		fmt.Println("ERROR - Not found")
	} else {
		fmt.Println("GOOD - Found")
		fmt.Println(len(node))
	}

	node = xmlquery.Find(doc, "//myns:child")
	if node == nil {
		fmt.Println("ERROR - Not found")
	} else {
		fmt.Println("GOOD - Found")
		fmt.Println(len(node))
	}
}
```

**Comment by zhengchun** [comment]
Thanks for the feedback. This is a bug, `//myns:child[@id='1']` should be found one element, I am fixing.

**Comment by zhengchun** [comment]
Update your [xpath](https://github.com/antchfx/xpath) and [xmlquery](https://github.com/antchfx/xmlquery) packages, looks the output is correct now.

```
### WILL WORK
GOOD - Found
1
ERROR - Not found
### WILL FAIL
ERROR - Not found
GOOD - Found
1
GOOD - Found
2
```

And an other thing is that the below XML document is invalid, the package should return an error, but nothing. 😄 
```
<root>
  <myns:child id="1">value 1</myns:child>
  <myns:child id="2">value 2</myns:child>
</root>
```
is invalid XML document.

**Comment by lazize** [comment]
Great, I tested and now it works fine with my use-case.

> And an other thing is that the below XML document is invalid, the package should return an error, but nothing. 😄

At least now you know.

**Comment by lazize** [comment]
With the latest version I am getting this error with the XML below.
`xmlquery: invalid XML document, namespace is missing`

Note that `root` node has `namespace` also.
```go
	`<myns:root xmlns:myns="bla bla bla">
	  <myns:child id="1">value 1</myns:child>
	  <myns:child id="2">value 2</myns:child>
	</myns:root>`
````

**Comment by lazize** [comment]
Great, now both works. I will close it.

**Comment by alranel** [comment]
Actually, when parsing an XML with namespaces we don't know what alias is used in the document but we know the actual namespace URI.  So we can't hard-code a query like `//myns:child`; we should be able to set a the `myns => http://..uri...` alias at parsing time, and that should work even if that namespace was aliased in any other way in the input document.

**Comment by lazize** [comment]
@alranel so what is your proposal?
