### ISSUE TITLE
`invalid XML document` on subsequent StreamParser.Read() with default/non-prefixed namespace

### ISSUE THREAD

**Issue by uw-dc** [antchfx/xmlquery#111]
The following example:

```
<Objects xmlns="http://example.com/schema/2007/someschema">
    <Object id="ObjectA">ObjectA</Object>
    <Object id="ObjectB">ObjectB</Object>
    <Object id="ObjectC">ObjectD</Object>
</Objects>
```

Results in...

```
 xmlquery: invalid XML document, namespace http://example.com/schema/2007/someschema is missing
```

... on the second StreamParser read.

This is demonstrated in [this](https://github.com/uw-dc/xmlquery/blob/29efaaca451b8a14a0ac06c881c6b22bd0f0a1d0/parse_test.go#L532) test, which I've added on a fork/branch.

I think this is because the `space2prefix` map does not get re-populated with the default/non-prefixed namespace after the first `sp.Read()`.

Still investigating and familiarising myself with the codebase. In the meantime, any insight would be appreciated.
Thanks.

**Comment by uw-dc** [comment]
I found [disabling strict decoding](https://github.com/antchfx/xmlquery/blob/f30da8037a2841662e7d3a367dbec829d8fd6ba5/parse.go#L120) makes for an effective work around

```
options := xmlquery.ParserOptions{
    Decoder: &xmlquery.DecoderOptions{
        Strict: false,
    },
}

streamParser, err := xmlquery.CreateStreamParserWithOptions(xmlFile, options, xmlMap.RowsPath)
```

**Comment by uw-dc** [comment]
That's not really solved though is it?
It's working around the problem. I'm not parting HTML, It's perfectly valid XML which should work with strict parsing.

**Comment by zhengchun** [comment]
the local variable `space2prefix` will cached the `NamespaceURL` values when first parse XML document using `Parse()`, it can works with the `Parse()`.

With the `CreateStreamParser()` method, the`space2prefix` value is empty when you second invoke the `Read()` memthod.
