### ISSUE TITLE
How to get attribute value

### ISSUE THREAD

**Issue by packetq** [antchfx/xmlquery#13]
Hi,

I've been trying to figure out how to get an attribute value. I can get a list with one item based on the xquery @ syntax, but it is not an attribute node.

Thanks,
-G

**Comment by zhengchun** [comment]
method 1, call `SelectAttr()`: 

https://godoc.org/github.com/antchfx/xmlquery#Node.SelectAttr

method 2, use `@xxx` XPath expression:

```go
for _,node:=range doc.SelectElements("//a/@href"){
    fmt.Println(node.InnerText())
}

```

**Comment by packetq** [comment]
Perfect!

Thanks,
-G
