### ISSUE TITLE
Disregard namespace prefix

### ISSUE THREAD

**Issue by devangvira** [antchfx/xmlquery#15]
While parsing a XML document having the following structure:
`<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:pd="http://xmlns.xyz.com/process/2003" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <pd:activity name="Invoke Request-Response Service">
        <pd:type>RequestReplyActivity</pd:type>
        <pd:resourceType>OpClientReqActivity</pd:resourceType>
        <pd:x>300</pd:x>
        <pd:y>80</pd:y>
        <config>
...`

I have to specify the namespace prefix for parsing the tags like:

`fmt.Println("Parsing process")
	for i, n := range xmlquery.Find(doc, "//pd:ProcessDefinition/pd:activity/pd:type") {
		fmt.Printf("#%d %s\n", i, n.InnerText())
	}`

Is there a way to disregard the namespace prefix? So that I can just look for `xmlquery.Find(doc, "//ProcessDefinition/activity/type")`

**Comment by zhengchun** [comment]
Sorry, there is no way to get it. if XML have a namespace, you must specify a prefix to query. you can see this https://github.com/antchfx/xmlquery/issues/1

**Comment by devangvira** [comment]
So then is there a way/function to fetch the namespaces (prefixes and URIs) from a XML document?

**Comment by zhengchun** [comment]
Maybe this method can help you if you don't care about namespace in XML.  you can replace all `pd:` string to empty string before parse XML document, then query by `"//ProcessDefinition/activity/type"`.

On the other hand, https://godoc.org/github.com/antchfx/xmlquery#NodeNavigator.Prefix can get namespace value.

```go
for n := doc.FirstChild; n != nil; n = n.NextSibling {
	fmt.Println(n.Prefix)
}
```

**Comment by sgoldenb** [comment]
You can remove the namespaces with a function like this.

`
func removeNamespace(n *xmlquery.Node) {
	n.Prefix = ""
	for child := n.FirstChild; child != nil; child = child.NextSibling {
		removeNamespace(child)
	}
`

**Comment by BigMak7410** [comment]
Hi @zhengchun . Thanks for your work.
I agree with @devangvira, we are missing the search for an element with any namespace, for example:
xmlquery.Find(doc, "//*:ProcessDefinition/*:activity/*:type")
By the way, it lacks Node.Remove/Delete method.
Thanks!

**Comment by nathanclayton** [comment]
I think that the bigger issue is the fact that you have to use the same namespace prefix as in the source document. This prefix could be arbitrarily chosen by the document creator, leaving you to try to figure it out if you're accepting documents from 3rd parties.

Would it be possible to pass in to the Find an optional set of schemas as a `map[string]string` of abbreviations/namespaces that are used for your namespace aliasing?

For the example before:
```
<?xml version="1.0" encoding="UTF-8"?>
<pd:ProcessDefinition xmlns:pd="http://xmlns.xyz.com/process/2003" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<pd:activity name="Invoke Request-Response Service">
<pd:type>RequestReplyActivity</pd:type>
<pd:resourceType>OpClientReqActivity</pd:resourceType>
<pd:x>300</pd:x>
<pd:y>80</pd:y>
</pd:activity>
</pd:ProcessDefinition>
```

and then in your find, you could do something like:
```
var nsMap map[string]string = map[string]striong{
  "q": "http://xmlns.xyz.com/process/2003",
  "r": "http://www.w3.org/1999/XSL/Transform",
  "s": "http://www.w3.org/2001/XMLSchema",
}
xmlquery.Find(doc, "//q:ProcessDefinition/q:activity/q:type", nsMap)
```

**Comment by arthurdarcet** [comment]
+1 to what @nathanclayton proposed - this is what lxml is doing in Python.

as a work around, you can use `namespace-uri() = '…' and local-name() = '…'`

**Comment by suntong** [comment]
Hi @arthurdarcet, thanks for the suggestion, would you explain how would using `namespace-uri()` and `local-name()` can simplify the following xpath query please?

`"//pd:ProcessDefinition/pd:activity/pd:type"`

Sorry I wasn't able to put 2 and 2 together myself. thanks

**Comment by arthurdarcet** [comment]
@suntong of course: `"//*[namespace-uri()='http://xmlns.xyz.com/process/2003' and local-name()='ProcessDefinition']/*[namespace-uri()='http://xmlns.xyz.com/process/2003' and local-name()='activity']/*[namespace-uri()='http://xmlns.xyz.com/process/2003' and local-name()='type']"`

**Comment by suntong** [comment]
1. Thanks @arthurdarcet 

2. +1 to @nathanclayton's suggestion, which gives the perfect solution to the problem from #1:

  > when parsing an XML with namespaces we don't know what alias is used in the document but we know the actual namespace URI. So we can't hard-code a query like //myns:child; we should be able to set a the myns => http://..uri... alias at parsing time, and that should work even if that namespace was aliased in any other way in the input document.

Please consider.

**Comment by zhengchun** [comment]
in the latest of [xpath v1.2.4](https://github.com/antchfx/xpath/releases/tag/v1.2.4), using `CompileWithNS()`  method to pass a prefix and namespaceURL map. It is like the below code:

```go
expr, _ := xpath.CompileWithNS("//pd:x", map[string]string{"pd": "http://xmlns.xyz.com/process/2003"})
node := xmlquery.QuerySelector(doc, expr)
```

closed  this issue.
