### ISSUE TITLE
Create new XML from extraced nodes

### ISSUE THREAD

**Issue by dominikmeixner** [antchfx/xmlquery#16]
Can i create a new XML file frome the nodes I've extracted? 
I used ```n := xmlquery.FindOne(doc, "//part[@id='P1']")```  to get the part of the XML i needed. Now i want to write that part into a new xml file.

**Comment by zhengchun** [comment]
Yes, you can call [OutputXML(bool)](https://godoc.org/github.com/antchfx/xmlquery#Node.OutputXML) method to get all the body of this node, including its child nodes.

```
n := xmlquery.FindOne(doc, "//part[@id='P1']")
xml := n.OutputXML(true)
f, err := os.Open("a.xml")
w := bufio.NewWriter(f)
w.WriteString(xml)
```

**Comment by dominikmeixner** [comment]
Thanks, that did work, but not perfectly. Is there a charakter limitation? Because I am unable to write the  entire text into the xml file. I don't get any errors.

**Comment by zhengchun** [comment]
No any limitation. You can print a `n.OutputXML(true)` value on console. If it is lost some data, you can submit you test file and code.

**Comment by dominikmeixner** [comment]
I actually did that already and no data has been lost. Should I submit anyways?

**Comment by zhengchun** [comment]
OK, so  what does it mean you unable to write the entire text into the xml file?

**Comment by dominikmeixner** [comment]
My String gets cut off at some point, approximately after a third.

**Comment by zhengchun** [comment]
can you paste your code and file?

**Comment by dominikmeixner** [comment]
I think I found the problem, the buffer seems to be too small. Is there a possibility to split the node into two and paste them in seperately?

**Comment by zhengchun** [comment]
you can visit the project docs: https://godoc.org/github.com/antchfx/xmlquery
