### ISSUE TITLE
Order of elements have an impact on some searches

### ISSUE THREAD

**Issue by ToadKing** [antchfx/xmlquery#23]
https://play.golang.org/p/IJSJSlRx3ej

These two documents should have the same results, but it looks like in the second document, the wrong namespace-uri() is being returned for the `<foo:Baz/>` element.

**Comment by zhengchun** [comment]
Closed #https://github.com/antchfx/xpath/commit/054c26a949af701c5098a1d0ff9512dc3d4a81b9
