### ISSUE TITLE
Can't select nth element of a certain Node.

### ISSUE THREAD

**Issue by dominikmeixner** [antchfx/xmlquery#24]
I am trying to get all of the `<repeat>`  Nodes of my MusicXML-File. I know they are there, I can also find them with `xmlquery.Find()` but I am unable to select more than the **first** and the **second** repeat Node, eventhough there are four of them.
Is there a way to extract them from the `xmlquery.Find()` Query?
`FindRepeat := xmlquery.FindOne(parsedXml, "(//repeat/parent::*/parent::measure/@number)[2]")`
also not working with 
`FindRepeat := xmlquery.FindOne(parsedXml, "(//measure[.//repeat])[3]").OutputXML(true)`

**Comment by zhengchun** [comment]
Fixed this bug at antchfx/xpath@c407737, getting the latest `xpath` package to fix.
