### ISSUE TITLE
LoadURL doesn't check status code

### ISSUE THREAD

**Issue by tzachshabtay** [antchfx/xmlquery#28]
When we call LoadURL on a url which returns an error status code (like 403 "forbidden" for example), the status code is both ignored and not passed.

See here:
https://github.com/antchfx/xmlquery/blob/fe009d4cc63c3011f05e1dfa75a27899acccdf11/node.go#L193

So we get a nil err and a corrupted document back.

LoadURL should either check that the status code is in the 200s and if not return an err, or alternatively return an object which contains the status code (or the complete response object?) with the document so we can check it ourselves.

**Comment by zhengchun** [comment]
You should handle HTTP request by yourself. `LoadURL()` just provide a simple way to load a HTTP resource.

**Comment by tanishq-dubey** [comment]
Correct me if I am wrong, but by providing an interface to "load a document from a URL", or indeed, any external source, would it not make sense to always be conservative and throw errors? If this is not the case, and I must handle all loading myself, then the library should not provide a function that implies that it would do correct loading.

**Comment by zhengchun** [comment]
Sorry, I have no plans to improve `LoadURL()`. I encourage everyone handle HTTP request by self and don't dependence this function. In fact, You can easy add `gzip` flag or compatible with non-utf8  in implementation HTTP request handle.
