### ISSUE TITLE
substring-before always returns <nil> node

### ISSUE THREAD

**Issue by srebhan** [antchfx/xmlquery#29]
When executing the following code 
```golang
package main

import (
	"fmt"
	"strings"

	"github.com/antchfx/xmlquery"
)

func main(){
	xml := `
	<?xml version="1.0"?>
	<Test>
	  <Variable Name="test-a-b/c"/>
	</Test>
	`
	query := "/Test/Variable/@Name"
	// query := "substring-before(/Test/Variable/@Name, '-')"

	// Parse the XML
	doc, err := xmlquery.Parse(strings.NewReader(xml))
	if err != nil {
		panic(err)
	}

	// Queries
	node, err := xmlquery.Query(doc, query)
	if err != nil {
		panic(err)
	}
	if node == nil {
		fmt.Print("Node is nil\n")
	} else {
		fmt.Printf("Result: %v\n", node.InnerText())
	}
}
```
with the first query, the node is found correctly and I do get the text of the attribute '_test-a-b/c_' as expected.

However, when using the second query with `substring-before` I do get a `nil` `node` and the print-out is '_Node is nil_', when the expected result is the string '_test_'.

Is there an error in the code above or is this an issue in xmlquery?

**Comment by zhengchun** [comment]
Use [xpath.Eval()](https://godoc.org/github.com/antchfx/xpath#Expr.Evaluate) instead of `xmlquery.Query()`. The `xmlquery.Query()` function only executing a query(including logical operation) not do computing. 

```
// Parse the XML
	doc, err := xmlquery.Parse(strings.NewReader(xml))
	if err != nil {
		panic(err)
	}
	query = "substring-before(/Test/Variable/@Name, '-')"
	exp := xpath.MustCompile(query)
	v := exp.Evaluate(xmlquery.CreateXPathNavigator(doc))
	fmt.Println(v.(string))
```
