### ISSUE TITLE
XML QueryAll not finding all nodes

### ISSUE THREAD

**Issue by vbisbest** [antchfx/xmlquery#67]
I have an xml document and trying to pull all "con:resource" nodes out of it.   For some reason, xmlquery is only finding 2 nodes when there are 8 that should be returned.   "Find" has the same issue.  I have tested this with an online xpath tool and it works properly.  

```
r := bufio.NewReader(file)
doc, _ := xmlquery.Parse(r)
nodes, _ := xmlquery.QueryAll(doc, "/con:soapui-project/con:interface/con:resource")
```

  Here is my XML document.

`<?xml version="1.0" encoding="UTF-8"?>
<con:soapui-project id="5f1867b5-0c77-4a1d-bd44-5056d336746c" activeEnvironment="Default" name="REST Project 1" resourceRoot="" soapui-version="5.6.0" abortOnError="false" runType="SEQUENTIAL" xmlns:con="http://eviware.com/soapui/config">
  <con:settings/>
  <con:interface xsi:type="con:RestService" id="9a303f1c-0e70-40d7-9ccd-075a3cf567a8" wadlVersion="http://wadl.dev.java.net/2009/02" name="http://localhost:3008" type="rest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <con:settings/>
    <con:definitionCache type="TEXT" rootPart=""/>
    <con:endpoints>
      <con:endpoint>http://localhost:3008
      </con:endpoint>
    </con:endpoints>
    <con:resource name="Activities" path="/api/v1/activities/" id="877e2013-af6f-4bd8-830a-cd3a0b6e5711">
      <con:settings/>
      <con:parameters/>
      <con:method name="Activities 1" id="219fa902-449e-4e15-9785-12f5584346b4" method="POST">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>405 415
          </con:status>
          <con:params/>
          <con:element xmlns:act="http://localhost/api/v1/activities/">act:Fault
          </con:element>
        </con:representation>
        <con:representation type="REQUEST">
          <con:mediaType>application/x-www-form-urlencoded
          </con:mediaType>
          <con:params/>
        </con:representation>
        <con:representation type="REQUEST">
          <con:mediaType>application/json
          </con:mediaType>
          <con:params/>
        </con:representation>
        <con:representation type="FAULT">
          <con:mediaType xsi:nil="true"/>
          <con:status>400
          </con:status>
          <con:params/>
          <con:element>data
          </con:element>
        </con:representation>
        <con:representation type="FAULT">
          <con:mediaType xsi:nil="true"/>
          <con:status>400
          </con:status>
          <con:params/>
          <con:element>data
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element>Response
          </con:element>
        </con:representation>
        <con:representation type="FAULT">
          <con:mediaType xsi:nil="true"/>
          <con:status>400
          </con:status>
          <con:params/>
          <con:element>data
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="92738129-2563-4820-a570-d89c11d5c68b" mediaType="application/json" postQueryString="false">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request>    {
            "month": "1"
            }
          </con:request>
          <con:originalUri>http://localhost/api/v1/activities/
          </con:originalUri>
          <con:credentials>
            <con:authType>No Authorization
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters/>
          <con:parameterOrder/>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="{ISBN}" path="/api/v1/books/{ISBN}/" id="eae1274b-1995-49cd-8b91-71fe5880e642">
      <con:settings/>
      <con:parameters>
        <con:parameter>
          <con:name>ISBN
          </con:name>
          <con:value>ISBN
          </con:value>
          <con:style>TEMPLATE
          </con:style>
          <con:default>ISBN
          </con:default>
        </con:parameter>
      </con:parameters>
      <con:method name="Method 1" id="ddade492-49a9-4e84-98fd-cc2ae42d9a9e" method="GET">
        <con:settings/>
        <con:parameters/>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element xmlns:ns="http://localhost/api/v1/books/978-93-80658-74-2/">ns:Response
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="5e49b2d9-c74d-43f7-8dbe-1f4bf77d745f" mediaType="application/json">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request/>
          <con:originalUri>http://localhost/api/v1/books/978-93-80658-74-2/
          </con:originalUri>
          <con:credentials>
            <con:authType>No Authorization
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters>
            <entry key="ISBN" value="978-93-80658-74-2" xmlns="http://eviware.com/soapui/config"/>
          </con:parameters>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="{ID}" path="/api/v1/exams/{ID}/" id="43ee5bdd-3f03-48c5-8a23-c551ef167178">
      <con:settings/>
      <con:parameters>
        <con:parameter>
          <con:name>ID
          </con:name>
          <con:value>ID
          </con:value>
          <con:style>TEMPLATE
          </con:style>
          <con:default>ID
          </con:default>
        </con:parameter>
      </con:parameters>
      <con:method name="Method 1" id="783c0b15-fcd1-453a-809e-90cf1e75cc99" method="GET">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>401
          </con:status>
          <con:params/>
          <con:element xmlns:ns="http://localhost/api/v1/exams/123/">ns:Fault
          </con:element>
        </con:representation>
        <con:representation type="FAULT">
          <con:mediaType>text/plain
          </con:mediaType>
          <con:status>500
          </con:status>
          <con:params/>
          <con:element>data
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element xmlns:ns="http://localhost/api/v1/exams/123/">ns:Response
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="64d0e92e-f844-4965-b51c-0c88aa35d237" mediaType="application/json">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request/>
          <con:originalUri>http://localhost/api/v1/exams/123/
          </con:originalUri>
          <con:credentials>
            <con:selectedAuthProfile>Profile 1
            </con:selectedAuthProfile>
            <con:authType>OAuth 2.0
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters>
            <entry key="ID" value="MQ==" xmlns="http://eviware.com/soapui/config"/>
          </con:parameters>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="{ID}" path="/api/v1/articles/{ID}/" id="7c408539-9777-41bd-8500-f2b8429097c2">
      <con:settings/>
      <con:parameters>
        <con:parameter>
          <con:name>ID
          </con:name>
          <con:value>ID
          </con:value>
          <con:style>TEMPLATE
          </con:style>
          <con:default>ID
          </con:default>
        </con:parameter>
      </con:parameters>
      <con:method name="Method 1" id="0ecd23e4-8a88-4f5d-bfab-a8dea0ee7c53" method="GET">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType xsi:nil="true"/>
          <con:status>404
          </con:status>
          <con:params/>
          <con:element>data
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element xmlns:ns="http://localhost/api/v1/articles/1/">ns:Response
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="135ece4c-2535-4d48-a952-4806815c01bf" mediaType="application/json">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request/>
          <con:originalUri>http://localhost/api/v1/articles/1/
          </con:originalUri>
          <con:credentials>
            <con:authType>No Authorization
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters>
            <entry key="ID" value="2" xmlns="http://eviware.com/soapui/config"/>
          </con:parameters>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="advertisements" path="/api/v1/advertisements/" id="542fced1-12cf-485e-8ac3-a3952a020a54">
      <con:settings/>
      <con:parameters/>
      <con:method name="Method 1" id="b598531b-0c77-419a-ba8c-489aa796930f" method="POST">
        <con:settings/>
        <con:parameters/>
        <con:representation type="REQUEST">
          <con:mediaType>application/json
          </con:mediaType>
          <con:params/>
        </con:representation>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>401
          </con:status>
          <con:params/>
          <con:element xmlns:adv="http://localhost/api/v1/advertisements/">adv:Fault
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>201
          </con:status>
          <con:params/>
          <con:element xmlns:adv="http://localhost/api/v1/advertisements/">adv:Response
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="563b224f-319c-46d8-bc8c-070eddc43c8c" mediaType="application/json" postQueryString="false">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request>    {
            "headline": "Test",
            "info": "Some Info",
            "price":  13.03
            }
          </con:request>
          <con:originalUri>http://localhost/api/v1/advertisements/
          </con:originalUri>
          <con:credentials>
            <con:selectedAuthProfile>Profile 1
            </con:selectedAuthProfile>
            <con:authType>OAuth 2.0
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters/>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="advertisements" path="/api/v1/advertisements/" id="f304fd91-8e04-46e9-9b79-5cfd87fcb3e4">
      <con:settings/>
      <con:parameters/>
      <con:method name="Method 1" id="b061307d-a62d-46f6-9344-2be9d42fbbd7" method="GET">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>401
          </con:status>
          <con:params/>
          <con:element xmlns:adv="http://localhost/api/v1/advertisements/">adv:Fault
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element>Response
          </con:element>
        </con:representation>
        <con:request name="Request 1" id="835e390c-a802-4609-9686-e741cb69afb8" mediaType="application/json">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request/>
          <con:originalUri>http://localhost/api/v1/advertisements/
          </con:originalUri>
          <con:credentials>
            <con:selectedAuthProfile>Profile 1
            </con:selectedAuthProfile>
            <con:authType>OAuth 2.0
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters/>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="trains" path="/api/v1/trains/" id="4cfb0905-0fff-4272-87cd-56c371453d29">
      <con:settings/>
      <con:parameters/>
      <con:method name="Method 1" id="9eca62c0-db59-4691-a821-b876d99f0aa7" method="POST">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>405
          </con:status>
          <con:params/>
          <con:element xmlns:tra="http://localhost/api/v1/trains/">tra:Fault
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element xmlns:tra="http://localhost/api/v1/trains/">tra:Response
          </con:element>
        </con:representation>
        <con:representation type="REQUEST">
          <con:mediaType>application/json
          </con:mediaType>
          <con:params/>
        </con:representation>
        <con:request name="Request 1" id="3d14b0d1-f52e-4eef-8579-6073df9dac95" mediaType="application/json" postQueryString="false">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request>{
            "PNR": "9875-4581-234"
            }
          </con:request>
          <con:originalUri>http://localhost/api/v1/trains/
          </con:originalUri>
          <con:credentials>
            <con:authType>No Authorization
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters/>
        </con:request>
      </con:method>
    </con:resource>
    <con:resource name="Copy of trains" path="/api/v1/trains/" id="4cfb0905-0fff-4272-87cd-56c371453d29">
      <con:settings/>
      <con:parameters/>
      <con:method name="Method 1" id="9eca62c0-db59-4691-a821-b876d99f0aa7" method="POST">
        <con:settings/>
        <con:parameters/>
        <con:representation type="FAULT">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>405
          </con:status>
          <con:params/>
          <con:element xmlns:tra="http://localhost/api/v1/trains/">tra:Fault
          </con:element>
        </con:representation>
        <con:representation type="RESPONSE">
          <con:mediaType>application/json
          </con:mediaType>
          <con:status>200
          </con:status>
          <con:params/>
          <con:element xmlns:tra="http://localhost/api/v1/trains/">tra:Response
          </con:element>
        </con:representation>
        <con:representation type="REQUEST">
          <con:mediaType>application/json
          </con:mediaType>
          <con:params/>
        </con:representation>
        <con:request name="Request 1" id="3d14b0d1-f52e-4eef-8579-6073df9dac95" mediaType="application/json" postQueryString="false">
          <con:settings>
            <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
            </con:setting>
          </con:settings>
          <con:endpoint>http://localhost:3008
          </con:endpoint>
          <con:request>{
            "PNR": "9875-4581-234"
            }
          </con:request>
          <con:originalUri>http://localhost/api/v1/trains/
          </con:originalUri>
          <con:credentials>
            <con:authType>No Authorization
            </con:authType>
          </con:credentials>
          <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
          <con:jmsPropertyConfig/>
          <con:parameters/>
        </con:request>
      </con:method>
    </con:resource>
  </con:interface>
  <con:testSuite id="98e84e24-6fbc-4ac2-aa44-c86b184add0d" name="TestSuite 1">
    <con:settings/>
    <con:runType>SEQUENTIAL
    </con:runType>
    <con:testCase id="2e63373c-bee1-4f1b-acaf-bec9dd757661" failOnError="true" failTestCaseOnErrors="true" keepSession="false" maxResults="0" name="TestCase 1" searchProperties="true">
      <con:settings/>
      <con:testStep type="restrequest" name="activities" id="fc4e48cf-8b86-458c-97f0-003d87bd9278">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/activities/" methodName="Activities 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="activities" id="92738129-2563-4820-a570-d89c11d5c68b" mediaType="application/json" postQueryString="false">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request>    {
              "month": "1"
              }
            </con:request>
            <con:originalUri>http://localhost/api/v1/activities/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters/>
            <con:parameterOrder/>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="books" id="90c09b3d-6316-46ae-8624-364cc511e153">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/books/{ISBN}/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="books" id="5e49b2d9-c74d-43f7-8dbe-1f4bf77d745f" mediaType="application/json">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request/>
            <con:originalUri>http://localhost/api/v1/books/978-93-80658-74-2/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters>
              <entry key="ISBN" value="978-93-80658-74-2" xmlns="http://eviware.com/soapui/config"/>
            </con:parameters>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="exams" id="568da715-92c0-44d1-8074-4c98c7d9e09b">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/exams/{ID}/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="exams" id="64d0e92e-f844-4965-b51c-0c88aa35d237" mediaType="application/json">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request/>
            <con:originalUri>http://localhost/api/v1/exams/123/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters>
              <entry key="ID" value="MQ==" xmlns="http://eviware.com/soapui/config"/>
            </con:parameters>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="articles" id="cb2e49af-3b59-4e33-b2c4-b2fe2734f98e">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/articles/{ID}/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="articles" id="135ece4c-2535-4d48-a952-4806815c01bf" mediaType="application/json">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request/>
            <con:originalUri>http://localhost/api/v1/articles/1/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters>
              <entry key="ID" value="2" xmlns="http://eviware.com/soapui/config"/>
            </con:parameters>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="advertisements post" id="71295272-9343-46cd-b4cc-dda8898f9ff5">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/advertisements/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="advertisements post" id="563b224f-319c-46d8-bc8c-070eddc43c8c" mediaType="application/json" postQueryString="false">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request>    {
              "headline": "Test",
              "info": "Some Info",
              "price":  13.03
              }
            </con:request>
            <con:originalUri>http://localhost/api/v1/advertisements/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters/>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="advertisments get" id="9efaf3a1-596f-433c-b5d7-fb0fdda13250">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/advertisements/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="advertisments get" id="835e390c-a802-4609-9686-e741cb69afb8" mediaType="application/json" postQueryString="false">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request/>
            <con:originalUri>http://localhost/api/v1/advertisements/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters/>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:testStep type="restrequest" name="trains" id="1b1e5756-3f83-47a7-960c-eb122ae8901b">
        <con:settings/>
        <con:config service="http://localhost:3008" resourcePath="/api/v1/trains/" methodName="Method 1" xsi:type="con:RestRequestStep" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <con:restRequest name="trains" id="3d14b0d1-f52e-4eef-8579-6073df9dac95" mediaType="application/json" postQueryString="false">
            <con:settings>
              <con:setting id="com.eviware.soapui.impl.wsdl.WsdlRequest@request-headers">&lt;xml-fragment/>
              </con:setting>
            </con:settings>
            <con:endpoint>http://localhost:3008
            </con:endpoint>
            <con:request>{
              "PNR": "9875-4581-234"
              }
            </con:request>
            <con:originalUri>http://localhost/api/v1/trains/
            </con:originalUri>
            <con:credentials>
              <con:selectedAuthProfile>Profile 1
              </con:selectedAuthProfile>
              <con:authType>OAuth 2.0
              </con:authType>
            </con:credentials>
            <con:jmsConfig JMSDeliveryMode="PERSISTENT"/>
            <con:jmsPropertyConfig/>
            <con:parameters/>
          </con:restRequest>
        </con:config>
      </con:testStep>
      <con:properties/>
    </con:testCase>
    <con:properties/>
  </con:testSuite>
  <con:properties/>
  <con:wssContainer/>
  <con:oAuth2ProfileContainer>
    <con:oAuth2Profile>
      <con:name>Profile 1
      </con:name>
      <con:clientID>ALGGN0UmsY2Gb9cs3V4CEKMfpBJ2D2XZQXuTFfND
      </con:clientID>
      <con:clientSecret>mWM7pgvjtUSAtfaK8RXLjzOaLmurBxIWxMdQIQ0t1fSv9orqOnYr5wP5CaFN8DE18NiFiKKalQPu1WecmpbfoZCGYhMqMACz6i2WkWYs5E8gjXxqekjCyPkhBmO5n5EN
      </con:clientSecret>
      <con:authorizationURI>http://localhost:3008/oauth/token/
      </con:authorizationURI>
      <con:accessTokenURI>http://localhost:3008/oauth/token/
      </con:accessTokenURI>
      <con:redirectURI>http://localhost:3008/oauth/token/
      </con:redirectURI>
      <con:accessToken>RoLnzPen7koSoKcife1m6tSSfmknHm
      </con:accessToken>
      <con:accessTokenPosition>HEADER
      </con:accessTokenPosition>
      <con:oAuth2Flow>RESOURCE_OWNER_PASSWORD_CREDENTIALS
      </con:oAuth2Flow>
      <con:refreshAccessTokenMethod>AUTOMATIC
      </con:refreshAccessTokenMethod>
      <con:refreshToken>sdaitQ0rXgpy1nXEXskPr0sy42p37I
      </con:refreshToken>
      <con:accessTokenStatus>RETRIEVED_FROM_SERVER
      </con:accessTokenStatus>
      <con:accessTokenStartingStatus>RETRIEVED_FROM_SERVER
      </con:accessTokenStartingStatus>
      <con:accessTokenExpirationTime>36000
      </con:accessTokenExpirationTime>
      <con:accessTokenIssuedTime>1624624920
      </con:accessTokenIssuedTime>
      <con:manualAccessTokenExpirationTime>2
      </con:manualAccessTokenExpirationTime>
      <con:useManualAccessTokenExpirationTime>true
      </con:useManualAccessTokenExpirationTime>
      <con:manualAccessTokenExpirationTimeUnit>HOURS
      </con:manualAccessTokenExpirationTimeUnit>
      <con:resourceOwnerName>batman
      </con:resourceOwnerName>
      <con:resourceOwnerPassword>Batman@123
      </con:resourceOwnerPassword>
    </con:oAuth2Profile>
  </con:oAuth2ProfileContainer>
  <con:oAuth1ProfileContainer/>
</con:soapui-project>`

**Comment by zhengchun** [comment]
The parser is parsing your XML file got an error, not get valid XML.
