### ISSUE TITLE
OutputXML should not call EscapeText when node type is TextNode.

### ISSUE THREAD

**Issue by leavesster** [antchfx/xmlquery#73]
I think the OutputXML function should give same string as the xml file is shows, not escape text. Escape xml Attribute is enough.

when xml is
```xml
<?xml version="1.0" encoding="utf-8"?>
	<class_list>
		<student xml:space="preserve">
			<name xml:space="default"> 
			Robert 
			</name>
			<grade>A+</grade>
		</student>
	</class_list>`
```

User except the node's OutputXML give the same string, not escape '\n\t' to html escape string.

and I found xml will escape these string `&\n\t` to html `&amp;`. I think may be this is way you escape these string.

I think TextNode may not need this escape behavior, only Attr string need this behavior.

If you need a pr to fix this, I can create a pr. But this may break a lot of tests.

**Comment by zhengchun** [comment]
Hello, Is this the same as https://github.com/antchfx/xmlquery/issues/66?

**Comment by leavesster** [comment]
> Hello, Is this the same as https://github.com/antchfx/xmlquery/issues/66? 

not only whitespace,but also `\t\n`. these control strings will escape to &#xA;&#x9;&#x9;&#x9;

**Comment by leavesster** [comment]
maybe we need some examples, such as this original xml: 

```xml
<?xml version="1.0" encoding="utf-8"?>
<corpus xml:space="preserve">
	<p>Lorem	 
<a>ipsum</a> 
dolor</p>
</corpus>
```

if use `node.OutputXML(false)`, it will output 

```xml
<?xml version="1.0" encoding="utf-8"?><corpus xml:space="preserve">&#xA;&#x9;&#x9;&#x9;<p>Lorem&#x9; <a>ipsum</a> dolor</p>&#xA;&#x9;&#x9;</corpus>
```

maybe this function should keep these escape string `\t\n` as their default string, so the `node.OutputXML(false)` just output their original string

**Comment by leavesster** [comment]
> Hello, Is this the same as #66?

It is slightly different from #66 which wants to make whitespace configurable by user.

This issue does not want to escape `\t\n`, just keep origin string. This behavior will make some break change (when xml has `xml:space="preserve"`). but I think not escape `\t\n` maybe is more friendly to users.
