### ISSUE TITLE
nil pointer dereference at parse.go:145

### ISSUE THREAD

**Issue by hokumski** [antchfx/xmlquery#75]
Hi!

There's possible "nil pointer dereference" error at line 145 of parse.go, p.prev could be nil
```
AddSibling(p.prev.Parent, node)
```

(I have XML file causing this error)

**Comment by hokumski** [comment]
v1.3.8

```
parsed, err := xmlquery.Parse(strings.NewReader(string(xmlDataBytes)))
```

[publication-6430.xml.zip](https://github.com/antchfx/xmlquery/files/7685874/publication-6430.xml.zip)

**Comment by zhengchun** [comment]
v1.3.9 to fix
