### ISSUE TITLE
No error or panic when parsing non-XML

### ISSUE THREAD

**Issue by tuan-nxcr** [antchfx/xmlquery#86]
I was expecting `Parse` or `Query` to error out if I were to pass in something completely invalid, but it falls all the way through and throws a panic at the `println(query.Data)` instead:

```go
func TestXmlParse_1(t *testing.T) {
	//s := `<note>
	//<to>John</to>
	//<from>Smith</from>
	//<heading>Reminder</heading>
	//<body>Don't forget me this weekend!</body>
	//</note>`

	s := `{"NotXml":"ActuallyJson"}`

	parse, err := xmlquery.Parse(strings.NewReader(s))
	if err != nil {
		println(err.Error())
		t.Fail()
	}
	query, err := xmlquery.Query(parse, "//body/text()")
	if err != nil {
		println(err.Error())
		t.Fail()
	}
	println(query.Data)

}
```

using:
* github.com/antchfx/xmlquery v1.3.11

**Comment by zhengchun** [comment]
Add `if query != nil {}` to avoid throw a query is nil exception before `println(query.Data)`

**Comment by tuan-nxcr** [comment]
this is more of a question why `Parse` can proceed without any error when I give it invalid XML, not about how to handle a nil pointer exception.

**Comment by tuan-nxcr** [comment]
@zhengchun

Thanks for reopening! Yes, I was just looking for some way to validate that we have at least well-formed XML before proceeding to parsing (similar to what is recommended by the authors of the gjson package https://github.com/tidwall/gjson#validate-json).

My workaround for this right now is to precede the `xmlquery.Parse` step with:
```go
func isXml(mvrString string) bool {
	return xml.Unmarshal([]byte(mvrString), new(interface{})) == nil

}
```

**Comment by ssratkevich** [comment]
`xmlquery.Parse` and `xmlquery.ParseWithOptions` will produce error on non XMLs.

See: https://github.com/antchfx/xmlquery/pull/123
